blog/urls.py
import imp
from django.urls import URLPattern, path
from .views import (
    BlogDeleteView,
    BlogListView,
    BlogCreateView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)


app_name = "Blog"

urlpatterns = [
    path("", BlogListView.as_view(), name="home"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", BlogDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='Home'),
    path('blog/', include('blog.urls', namespace='Blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
        title = models.CharField(max_length=20)
        content = models.TextField(max_length=300)
        updated_on = models.DateTimeField(auto_now= True)
        created_on = models.DateTimeField(auto_now_add=True)

            
        def __str__(self):
            return self.title
        
        class Meta:
            ordering = ['-created_on']

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model= Post
        fields=('title','content')

blog/views.py
from dataclasses import fields
from multiprocessing import context
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy


class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()

        context = {"posts": posts}

        return render(request, "blog_list.html", context)


class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form = PostCreateForm
        context = {"form": form}
        return render(request, "blog_create.html", context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get("title")
                content = form.cleaned_data.get("content")

                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect("Blog:home")

        context = {}
        return render(request, "blog_create.html", context)


class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {"post": post}
        return render(request, "blog_detail.html", context)


class BlogUpdateView(UpdateView):
    model = Post
    fields = ["title", "content"]
    template_name = "blog_update.html"

    def get_success_url(self) -> str:
        pk = self.kwargs["pk"]
        return reverse_lazy("Blog:detail", kwargs={"pk": pk})


class BlogDeleteView(DeleteView):
    model = Post
    template_name = "blog_delete.html"
    success_url = reverse_lazy("Blog:home")

core/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import render, redirect


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'home.html',context)

core/templates/base.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.2/tailwind.min.css"
    />
    <title>Anonpost.</title>
    {% tailwind_css %}
  </head>
  <body>
    {% include 'navbar.html' %}  {% block content %} {% endblock content %}
    <br>
   
  </body>
  <footer> {% include 'footer.html'%} </footer>
</html>

core/templates/blog_create.html
{% extends 'base.html' %} {% block content %}
{% load tailwind_filters %}
<br>
<form action="POST"></form>
<div class="gap-5 grid  place-items-center">
  <form method="POST">
    <div class="shadow sm:rounded-md sm:overflow-hidden">
      <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
        <div class="grid grid-cols-0">
          <div class="col-span-3 sm:col-span-2">

            <label for="company-website" class="block text-sm font-medium text-gray-700"> {% csrf_token %}
              {{form|crispy}}</label>
          </div>
        </div>
        <p class="mt-2 text-sm text-gray-500">Write a short blog.</p>
      </div>


      <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
        <button type="submit"
          class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Submit</button>
      </div>
    </div>
  </form>
</div>
</form>


{% endblock content %}

core/templates/blog_delete.html
<form method="POST">
{% csrf_token %}

    <button type="submit">Delete</button>
    </form>

core/templates/blog_detail.html
{% extends 'base.html' %} {% block content %}

<br>
<div class="w-full max-w-sm px-4 py-3 mx-auto bg-white rounded-md shadow-md">


    <div class="flex items-center justify-between">
        <span
            class="px-3 py-1 text-xs text-blue-800 uppercase bg-blue-200 rounded-full dark:bg-blue-300 dark:text-blue-900">Anon-MINIPOST</span>
        <div class="flex flex-row-reverse">
            <form action="{% url 'Blog:delete' post.id %}">
                <button
                    class="z-30 block p-4 text-red-700 transition-all bg-red-100 border-2 border-white rounded-full hover:scale-110 focus:outline-none focus:ring active:bg-red-50"
                    type="submit">
                    <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                </button>
            </form>
            <form action="{% url 'Blog:update' post.id %}">
                <button
                    class="z-20 block p-4 text-blue-700 transition-all bg-blue-100 border-2 border-white rounded-full active:bg-blue-50 hover:scale-110 focus:outline-none focus:ring"
                    type="submit">
                    <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                        stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                    </svg>
                </button>
            </form>
        </div>
    </div>

    <div>
        <h1 class="mt-2 text-lg font-semibold text-gray-800">{{post.title}}</h1>
        <p class="mt-2 text-sm text-gray-600">{{post.content}}</p>
        <div class="flex flex-row-reverse">
            <br>
            <dd class="text-xs text-gray-500">{{ post.created_on}}</dd>
        </div>
    </div>

    <div>


        <div class="flex items-center justify-center mt-4">
            <a class="mr-2 text-gray-800 cursor-pointer dark:text-gray-400 hover:text-gray-700 ">
                <svg class="w-5 h-5 fill-current" xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'>
                    <path
                        d='M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z' />
                </svg>
            </a>

            <a class="mr-2 text-gray-800 cursor-pointer dark:text-gray-400 hover:text-gray-700">
                <svg class="w-5 h-5 fill-current" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M14.8283 12L16.2426 13.4142L19.071 10.5858C20.6331 9.02365 20.6331 6.49099 19.071 4.9289C17.5089 3.3668 14.9762 3.3668 13.4141 4.9289L10.5857 7.75732L11.9999 9.17154L14.8283 6.34311C15.6094 5.56206 16.8757 5.56206 17.6568 6.34311C18.4378 7.12416 18.4378 8.39049 17.6568 9.17154L14.8283 12Z" />
                    <path
                        d="M12 14.8285L13.4142 16.2427L10.5858 19.0711C9.02365 20.6332 6.49099 20.6332 4.9289 19.0711C3.3668 17.509 3.3668 14.9764 4.9289 13.4143L7.75732 10.5858L9.17154 12L6.34311 14.8285C5.56206 15.6095 5.56206 16.8758 6.34311 17.6569C7.12416 18.4379 8.39049 18.4379 9.17154 17.6569L12 14.8285Z" />
                    <path
                        d="M14.8284 10.5857C15.2189 10.1952 15.2189 9.56199 14.8284 9.17147C14.4379 8.78094 13.8047 8.78094 13.4142 9.17147L9.17154 13.4141C8.78101 13.8046 8.78101 14.4378 9.17154 14.8283C9.56206 15.2188 10.1952 15.2188 10.5857 14.8283L14.8284 10.5857Z" />
                </svg>
            </a>
        </div>
    </div>
</div>



{% endblock content %}

core/templates/blog_list.html
{% extends 'base.html' %} {% block content %}
{% load tailwind_filters %}
{% for post in posts %}
<!-- Section 1 -->
<section class="bg-white">
  <div class="w-full px-5 py-6 mx-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">

    <a class="relative block p-8 overflow-hidden border border-gray-100 rounded-lg"
      href="{% url 'Blog:detail' post.id %}">
      <span class="absolute inset-x-0 bottom-0 h-2  bg-gradient-to-r from-green-300 via-blue-500 to-purple-600"></span>

      <div class="justify-between sm:flex">
        <div>
          <h5 class="text-xl font-bold text-gray-900">
            {{post.title}}
          </h5>
        </div>

        <div class="flex-shrink-0 hidden ml-3 sm:block">
          <img class="object-cover w-16 h-16 rounded-lg shadow-sm"
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Annona_squamosa_fruit.jpg/1200px-Annona_squamosa_fruit.jpg"
            alt="" />
        </div>
      </div>

      <div class="mt-4 sm:pr-8">
        <p class="text-sm text-gray-500">
          {{post.content}}
        </p>
      </div>

      <dl class="flex mt-6">
        <div class="flex flex-col-reverse">
          <dt class="text-sm font-medium text-gray-600">Published</dt>
          <dd class="text-xs text-gray-500">{{ post.created_on}}</dd>
        </div>
      </dl>
    </a>
</section>



{% endfor %}
{% endblock content %}

core/templates/blog_update.html
{% extends 'base.html' %} {% block content %}
{% load tailwind_filters %}

<br>
<form action="POST"></form>
<div class="gap-5 grid  place-items-center">
        <form method="POST">
          <div class="shadow sm:rounded-md sm:overflow-hidden">
            <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
              <div class="grid grid-cols-0">
                <div class="col-span-3 sm:col-span-2">
                    
                  <label for="company-website" class="block text-sm font-medium text-gray-700"> {% csrf_token %} {{form|crispy}}</label>
                </div>
              </div>
              </div>

    
            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
              <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Update</button>
            </div>
          </div>
        </form>
      </div>
</form>


{% endblock content %}

core/templates/footer.html
<footer class="text-center">
    <div class="max-w-screen-xl px-4 py-12 mx-auto sm:px-6 lg:px-8">
      <div class="max-w-3xl mx-auto space-y-6">
        <div class="flex justify-center space-x-6">
          <a
            class="text-blue-500 hover:text-opacity-75"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Twitter"
          >
            <svg
              class="w-8 h-8"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"
              ></path>
            </svg>
          </a>
  
          <a
            class="text-gray-900 hover:text-opacity-75"
            href="www.github.com/zaindou"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="GitHub"
          >
            <svg
              class="w-8 h-8"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fill-rule="evenodd"
                d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                clip-rule="evenodd"
              ></path>
            </svg>
          </a>
  
          <a
            class="text-pink-600 hover:text-opacity-75"
            href="/dribbble"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Dribbble"
          >
            <svg
              class="w-8 h-8"
              fill="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                fill-rule="evenodd"
                d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10c5.51 0 10-4.48 10-10S17.51 2 12 2zm6.605 4.61a8.502 8.502 0 011.93 5.314c-.281-.054-3.101-.629-5.943-.271-.065-.141-.12-.293-.184-.445a25.416 25.416 0 00-.564-1.236c3.145-1.28 4.577-3.124 4.761-3.362zM12 3.475c2.17 0 4.154.813 5.662 2.148-.152.216-1.443 1.941-4.48 3.08-1.399-2.57-2.95-4.675-3.189-5A8.687 8.687 0 0112 3.475zm-3.633.803a53.896 53.896 0 013.167 4.935c-3.992 1.063-7.517 1.04-7.896 1.04a8.581 8.581 0 014.729-5.975zM3.453 12.01v-.26c.37.01 4.512.065 8.775-1.215.25.477.477.965.694 1.453-.109.033-.228.065-.336.098-4.404 1.42-6.747 5.303-6.942 5.629a8.522 8.522 0 01-2.19-5.705zM12 20.547a8.482 8.482 0 01-5.239-1.8c.152-.315 1.888-3.656 6.703-5.337.022-.01.033-.01.054-.022a35.318 35.318 0 011.823 6.475 8.4 8.4 0 01-3.341.684zm4.761-1.465c-.086-.52-.542-3.015-1.659-6.084 2.679-.423 5.022.271 5.314.369a8.468 8.468 0 01-3.655 5.715z"
                clip-rule="evenodd"
              ></path>
            </svg>
          </a>
        </div>
  
        <nav
          class="relative flex flex-wrap justify-center gap-8 p-8 text-sm font-bold border-4 border-black rounded-xl"
        >
          <a
            class="hover:opacity-75"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Website
          </a>
  
          <a
            class="hover:opacity-75"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Uses
          </a>
  
          <a
            class="hover:opacity-75"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Portfolio
          </a>
        </nav>
  
        <p class="max-w-lg mx-auto text-xs text-gray-500">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, natus
          tempore illo laborum nam, modi quam sequi amet quo quasi impedit iure
          eum similique pariatur alias exercitationem, porro perspiciatis esse.
          Corporis odit consequatur sint sequi.
  
          <a
            class="block mt-1 text-pink-600 underline decoration-wavy decoration-pink-500 hover:opacity-75"
            href="/"
            target="_blank"
            rel="noopener noreferrer"
          >
            External Link
          </a>
        </p>
  
        <p class="text-xs font-medium">2022 Douglas Anaya</p>
      </div>
    </div>
  </footer>

core/templates/home.html
{% extends 'base.html' %}

{% block content %}
<aside
  class="p-12 pt-48 sm:p-16 sm:pt-64 bg-gradient-to-r from-purple-600 to-blue-500"
>
  <div class="sm:items-end sm:justify-between sm:flex">
    <div class="max-w-xl">
      <p class="text-3xl font-bold text-white sm:text-4xl">
        It was never so easy to show your anonymous statuses.
      </p>
    </div>

    <a
      href="{% url 'Blog:home' %}"
      class="inline-block px-8 py-4 mt-4 text-blue-500 bg-white rounded-lg shadow-lg hover:opacity-75 sm:mt-0 sm:ml-8"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="w-5 h-5 sm:h-8 sm:w-8"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M17 8l4 4m0 0l-4 4m4-4H3"
        />
      </svg>
    </a>
  </div>
</aside>

{% endblock content %}

core/templates/navbar.html
<header class="bg-gray-50">
  <div class="max-w-screen-xl px-4 py-8 mx-auto sm:py-12 sm:px-6 lg:px-8">
    <div class="sm:justify-between sm:items-center sm:flex">
      <div class="text-center sm:text-left">
        <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl" >
          Welcome Back, Anonymous!
        </h1>

        <p class="mt-1.5 text-sm text-gray-500">
          Let's write a new mini-anonpost! 🎉
        </p>
      </div>
      <form action="{% url 'Blog:home' %}">
        <div class="flex flex-col gap-4 mt-4 sm:flex-row sm:mt-0 sm:items-center">
          <button type="submit"
            class="inline-flex items-center justify-center px-5 py-3 text-gray-500 transition bg-white border border-gray-200 rounded-lg hover:text-gray-700 focus:outline-none focus:ring"
            type="button">
            <span class="text-sm font-medium">View posts</span>

            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4 ml-1.5" fill="none" viewBox="0 0 24 24"
              stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round"
                d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
            </svg>
          </button>
      </form>
      <form action="{% url 'Blog:create' %}">
        <button type="submit"
          class="block px-5 py-3 text-sm font-medium text-white transition bg-indigo-600 rounded-lg hover:bg-indigo-700 focus:outline-none focus:ring"
          type="button">
          Create Post
        </button>
      </form>
    </div>
  </div>
  </div>
</header>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>